name 'mod_auth_cas'
version '0.0.1'
source 'git://github.com/vkojuharova/vagrant-iam-castest-poc.git'
author 'Harvard University'
license 'The President and Fellows of Harvard College'
summary 'Apache module to allow for Apache mod_auth_cas - CAS server integration'
description 'Installs mod_auth_cas Apache module'
project_page ''


## Add dependencies, if any:
dependency 'puppetlabs/apache', '>=0.9.0'

