mod 'common',
  :git => 'https://github.com/huit/puppet-common.git'

# Recognizes Amazon Linux properly
mod 'epel',
  :git => 'https://github.com/jwreeder/puppet-module-epel.git'

# This is currently a noop but will be supported in the future.
forge 'forge.puppetlabs.com'

# Install modules from the Forge
mod 'puppetlabs/apache', '0.9.0'
mod 'puppetlabs/stdlib', '4.1.0'
mod 'puppetlabs/firewall', '0.4.2'
mod 'puppetlabs/concat'

mod 'evenup/tomcat', '0.8.1'
mod 'evenup/java', '0.0.4'
mod 'evenup/logrotate', '1.0.3'
