name 'evenup-tomcat'
version '0.8.1'
author 'Justin Lambert <jlambert@letsevenup.com>'
license 'Apache'
project_page 'https://github.com/evenup/evenup-tomcat'
summary 'Manages tomcat.'
description 'Installs, configures, and runs the tomcat service'
dependency 'evenup/java', '>=0.0.1'
dependency 'evenup/logrotate'

