name 'iam-firewall'
version '0.0.1'
source 'git://github.com/vkojuharova/vagrant-iam-castest-poc.git'
author 'Harvard University'
license 'The President and Fellows of Harvard College'
summary 'IAM extension to puppetlabls Firewall Module'
description 'Manages Firewalls such as iptables'
project_page ''

## Add dependencies, if any:
dependency 'puppetlabs/firewall', '>= 0.4.2'